### ISSUE TITLE
Module installation

### ISSUE THREAD

**Issue by catalina-damian** [edoardopachera/IBS_scraper#10]
Create a function that checks if the necessary modules are installed on the user's computer. If some are not present, the function will install them automatically.

**Comment by catalina-damian** [comment]
@LGuetta I completed my part, can you please add your function?

**Comment by LGuetta** [comment]
@catalina-damian In my latest commit d2e3422d74450334a3ed09cbe73905c624837b7f, I uploaded the application of your function to the packages we use. I also added the correction for a bug generated by the new version of Numpy on Windows.
